# Generated by Django 3.2.7 on 2022-11-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20221115_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('publish_date',)},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TimeField(null=True),
        ),
    ]
